#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_graphql_entrypoint:
  path: /api/graphql
  controller: api_platform.graphql.action.entrypoint

authentication_token:
  path: /login
  methods: ['POST']

graphqlite_bundle:
  resource: '@GraphqliteBundle/Resources/config/routes.xml'
