doctrine:
    dbal:
        dbname: TMPLNR-20
        host: localhost
        port: 3306
        user: root
        password: Paradigm88!
        driver: pdo_mysql
        server_version: '8.0'
        charset: UTF8
        url: mysql://root:Paradigm88!@127.0.0.1:3306/TMPLNR-20
        types:
            uuid_binary: Ramsey\Uuid\Doctrine\UuidType
        mapping_types:
            uuid_binary: binary

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
