nelmio_cors:
    defaults:
        allow_credentials: true
        origin_regex: true
        allow_origin: ['^http://localhost:[0-9]+']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['*']
        expose_headers: ['Link', 'Location', 'Authorisation', 'Credentials', 'Set-Cookie']
        max_age: 3600
    paths:
        '^/': ~
